"""
Per-application proxy launcher.

Умный выбор метода проксирования:
- Chromium-браузеры → нативный --proxy-server (100% надёжно)
- Firefox → отдельный профиль с настройками прокси в user.js
- Остальные приложения → proxychains-windows (перехват Winsock)
- Fallback → переменные окружения HTTP_PROXY / ALL_PROXY
"""
import os
import subprocess
import logging
from pathlib import Path

from core.config import APP_DIR, CONFIG_DIR

logger = logging.getLogger(__name__)

PROXYCHAINS_GITHUB = "https://github.com/shunf4/proxychains-windows/releases"

PROXY_PROFILES_DIR = CONFIG_DIR / "proxy_profiles"

# ---- Поиск proxychains-windows ----

_SEARCH_DIRS = [
    APP_DIR / "tools",
    APP_DIR / "tools" / "proxychains",
    APP_DIR / "proxychains",
    APP_DIR,
]

_EXE_NAMES = [
    "proxychains.exe",
    "proxychains_win32_x64.exe",
    "proxychains_win32_x86.exe",
    "proxychains_pe.exe",
    "proxychains_pe64.exe",
    "proxychains64.exe",
]

# ---- Определение типа приложения ----

_CHROMIUM_NAMES = frozenset({
    "chrome.exe", "msedge.exe", "brave.exe", "vivaldi.exe",
    "chromium.exe", "opera.exe", "yandex.exe", "browser.exe",
})

_FIREFOX_NAMES = frozenset({"firefox.exe"})

_CREATE_NO_WINDOW = 0x08000000


def detect_app_type(exe_path: str) -> str:
    """Определяет тип приложения для выбора лучшего метода."""
    name = Path(exe_path).name.lower()
    if name in _CHROMIUM_NAMES:
        return "chromium"
    if name in _FIREFOX_NAMES:
        return "firefox"
    return "generic"


def find_proxychains_exe() -> str:
    """Ищет proxychains-windows в стандартных папках."""
    for d in _SEARCH_DIRS:
        if not d.is_dir():
            continue
        for name in _EXE_NAMES:
            p = d / name
            if p.exists():
                return str(p)
    return ""


def write_proxychains_conf(socks_port: int) -> Path:
    """Генерирует proxychains.conf для текущего SOCKS5-прокси."""
    conf = CONFIG_DIR / "proxychains.conf"
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    conf.write_text(
        "# Auto-generated by TorProxy Manager\n"
        "strict_chain\n"
        "proxy_dns\n"
        "remote_dns_subnet 224\n"
        "tcp_read_time_out 15000\n"
        "tcp_connect_time_out 8000\n"
        "\n"
        "[ProxyList]\n"
        f"socks5 127.0.0.1 {socks_port}\n",
        encoding="utf-8",
    )
    return conf


# ================================================================= Единая точка входа

def launch_proxied(target: str, socks_port: int) -> tuple:
    """
    Запускает приложение через Tor-прокси, выбирая лучший метод.
    Возвращает (subprocess.Popen, method_name: str).
    """
    app_type = detect_app_type(target)

    if app_type == "chromium":
        return _launch_chromium(target, socks_port), "proxy-server"

    if app_type == "firefox":
        return _launch_firefox(target, socks_port), "firefox-profile"

    # generic: proxychains → env fallback
    pc = find_proxychains_exe()
    if pc:
        conf = write_proxychains_conf(socks_port)
        return _launch_via_proxychains(target, pc, str(conf)), "proxychains"

    return _launch_via_env(target, socks_port), "env-proxy"


# ================================================================= Методы запуска

def _launch_chromium(target: str, socks_port: int) -> subprocess.Popen:
    """Chrome / Edge / Brave / Yandex — нативный флаг --proxy-server."""
    profile = PROXY_PROFILES_DIR / "chromium"
    profile.mkdir(parents=True, exist_ok=True)
    cmd = [
        target,
        f"--proxy-server=socks5://127.0.0.1:{socks_port}",
        "--host-resolver-rules=MAP * ~NOTFOUND , EXCLUDE 127.0.0.1",
        f"--user-data-dir={profile}",
        "--no-first-run",
        "--no-default-browser-check",
    ]
    logger.info(f"chromium launch: {cmd[0]} --proxy-server=socks5://127.0.0.1:{socks_port}")
    return subprocess.Popen(cmd)


def _launch_firefox(target: str, socks_port: int) -> subprocess.Popen:
    """Firefox — отдельный профиль с SOCKS5 в user.js."""
    profile = PROXY_PROFILES_DIR / "firefox"
    profile.mkdir(parents=True, exist_ok=True)

    # user.js перечитывается Firefox при каждом запуске
    (profile / "user.js").write_text(
        f'user_pref("network.proxy.type", 1);\n'
        f'user_pref("network.proxy.socks", "127.0.0.1");\n'
        f'user_pref("network.proxy.socks_port", {socks_port});\n'
        f'user_pref("network.proxy.socks_version", 5);\n'
        f'user_pref("network.proxy.socks_remote_dns", true);\n'
        f'user_pref("network.proxy.no_proxies_on", "");\n',
        encoding="utf-8",
    )

    cmd = [target, "-no-remote", "-profile", str(profile)]
    logger.info(f"firefox launch: -profile {profile}")
    return subprocess.Popen(cmd)


def _launch_via_proxychains(
    target: str,
    proxychains_exe: str,
    conf_path: str,
) -> subprocess.Popen:
    """Запуск через proxychains (полный перехват Winsock)."""
    cmd = [proxychains_exe, "-f", conf_path, target]
    logger.info(f"proxychains launch: {' '.join(cmd)}")
    kw = {}
    if os.name == "nt":
        kw["creationflags"] = _CREATE_NO_WINDOW
    return subprocess.Popen(cmd, **kw)


def _launch_via_env(target: str, socks_port: int) -> subprocess.Popen:
    """Запуск с переменными окружения (fallback, не все приложения поддерживают)."""
    env = os.environ.copy()
    proxy = f"socks5://127.0.0.1:{socks_port}"
    for k in (
        "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
        "http_proxy", "https_proxy", "all_proxy",
    ):
        env[k] = proxy
    logger.info(f"env-proxy launch: {target}")
    return subprocess.Popen([target], env=env)
